### ISSUE TITLE
menu_hover-highlight, form__button_hover-highlight

### ISSUE THREAD

**Issue by cjbars** [navras96/webdev#2]
неправильная трактовка БЭМ

модификатор не должен описывать модификацию стиля
```
.form__button_hover-highlight; /*это неверно*/
```

он должен описывать модификацию элемента
```
.form__button-active;
.form__button-disabled;
```
в вашем случае hover и все остальное не требует отдельного класса, можно внести все в основной класс.

**Comment by navras96** [comment]
`		<ul class="menu menu_hover-highlight">
			<li><a href="index.html">Start</a></li>
			<li><a href="about.html">About</a></li>
			<li class="menu__item_selected"><a>Top List</a></li>
		</ul>
`
"menu__item_selected"  <--- это, получается, тоже описание стиля, поэтому неверно?

**Comment by navras96** [comment]
Вот с Яндекса: 

> Название модификатора характеризует внешний вид («какой размер?», «какая тема?» и т. п. — «размер»: size_s, «тема»: theme_islands), состояние («чем отличается от прочих?» — «отключен»: disabled, «фокусированный»: focused) и поведение («как ведет себя?», «как взаимодействует с пользователем?» — «направление»: directions_left-top).

**Comment by navras96** [comment]
https://github.com/navras96/webdev/commit/67cf83e2eed5e68436624c2fa7a2eda2362a98e1
